[package]
name = "some-lib"
version = "0.3.0"
edition = "2021"
rust-version = "1.65.0"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[target.'cfg(loom)'.dependencies]
loom = "0.7.0"
